/**
 * Import the 智见点评 expert pack into the Expert Library knowledge root.
 *
 * Source layout (extracted zip):
 *   智见点评/专家库/BK-NNN_姓名.md
 *   智见点评/专家材料/<姓名>/<姓名>_专家Profile_BK-NNN.json (+ 原始材料/近期动态)
 *   智见点评/{SKILL.md, 专家分类框架_v1.md, 专家总表.md, 专家输出框架规范_*.md, 路由规则.md, 资料更新规范.md}
 *
 * Destination (captain workspace knowledge root):
 *   <knowledge>/experts/bk-0NN/…             material only (profile JSON/MD + source material)
 *   <knowledge>/scenarios/zhijian-review.json scenario definition
 *   <knowledge>/scenarios/zhijian-review/…   scenario material
 *   <knowledge>/shared/zhijian/…             framework docs
 *
 * Expert DEFINITIONS are NOT written here anymore: the 32 Zhijian experts are
 * builtin plugin data (src/zhijian/data/experts.generated.ts, regenerated by
 * scripts/build-zhijian-data.mjs). This script only imports the material
 * folders, framework docs, and the review scenario.
 *
 * Run: `node scripts/import-zhijian.mjs <source> <knowledgeRoot>` from the
 * project root (defaults: /tmp/zhijian-skill/智见点评 /root/zhijian/knowledge).
 */

import { mkdirSync, readdirSync, copyFileSync, writeFileSync, existsSync, statSync } from 'node:fs'
import { join, basename } from 'node:path'

const SRC = process.argv[2] ?? '/tmp/zhijian-skill/智见点评'
const KNOWLEDGE = process.argv[3] ?? '/root/zhijian/knowledge'

const SCENARIO_ID = 'zhijian-review'

function copyTree(src, dst) {
  mkdirSync(dst, { recursive: true })
  for (const entry of readdirSync(src)) {
    const from = join(src, entry)
    const to = join(dst, entry)
    if (statSync(from).isDirectory()) copyTree(from, to)
    else copyFileSync(from, to)
  }
}

// ── 1. expert material folders (definitions are builtin, see header note) ──
const expertLibraryDir = join(SRC, '专家库')
const materialRoot = join(SRC, '专家材料')
const expertIds = []

for (const file of readdirSync(expertLibraryDir)) {
  if (!file.endsWith('.md')) continue
  const m = file.match(/^BK-(\d+)_(.+)\.md$/)
  if (!m) continue
  const [, bkNum, realName] = m
  const bkId = `bk-${bkNum}`
  expertIds.push(bkId)

  // material: profile JSON + flattened MD + source material + recent dynamics
  const materialDir = join(materialRoot, realName)
  if (existsSync(materialDir)) copyTree(materialDir, join(KNOWLEDGE, 'experts', bkId))
  copyFileSync(join(expertLibraryDir, file), join(KNOWLEDGE, 'experts', bkId, `${basename(file, '.md')}.md`))

  console.log(`[ok] ${bkId} ${realName} ← material (${existsSync(materialDir) ? 'Profile+材料' : 'MD only'})`)
}

// ── 2. shared framework docs ─────────────────────────────────────────────────
const sharedZhijian = join(KNOWLEDGE, 'shared', 'zhijian')
mkdirSync(sharedZhijian, { recursive: true })
for (const doc of ['SKILL.md', '专家分类框架_v1.md', '专家总表.md', '专家输出框架规范_20260809.md', '资料更新规范.md', '路由规则.md']) {
  copyFileSync(join(SRC, doc), join(sharedZhijian, doc))
}
console.log(`[ok] shared/zhijian/ ← 6 framework docs`)

// ── 3. scenario definition ───────────────────────────────────────────────────
const scenario = {
  id: SCENARIO_ID,
  name: '智见点评·专家研讨',
  description: '针对给定材料（合作协议/政策文件/市场数据）组织智见点评专家团研讨：先精读拆解与口径核对，再按路由规则从政策制度、存量循环、宏观经济、居住服务等视角并行研判，最后按输出框架融合成研讨纪要。默认阵容可替换（在总表中按话题另选专家）。',
  experts: ['bk-003', 'bk-006', 'bk-004', 'bk-033', 'docs-coordinator', 'team-lead'],
  tasks: [
    {
      subject: '材料精读与要素拆解',
      description: '精读给定材料（附件路径见队长 goal），拆解核心要素：主体与目标、合作内容、合作机制、边界条款；登记材料口径与疑点。',
      expert: 'bk-006',
    },
    {
      subject: '政策支持与制度环境分析',
      description: '从政策制度视角分析：协议中政府支持事项的合规边界、营商环境、制度安排的意义与风险。',
      dependsOn: [0],
      expert: 'bk-003',
    },
    {
      subject: '宏观经济与产业定位分析',
      description: '从宏观经济与产业视角分析：旅居产业在区域经济中的定位、市场空间、产业带动力与周期判断。',
      dependsOn: [0],
      expert: 'bk-004',
    },
    {
      subject: '存量循环与居住服务生态视角',
      description: '从存量盘活与居住服务视角分析：存量资产改造旅居地产的路径、住房租赁与闲置资产运营、服务生态与人才培养。',
      dependsOn: [0],
      expert: 'bk-033',
    },
    {
      subject: '融合研讨纪要',
      description: '按智见点评输出框架整合各视角研判：主基调为锚，观点按「支撑主基调 / 边界条件 / 风险提示」归位；讨论稿形态（可标注分类·首字母），口径与匿名化规范见 shared/zhijian/SKILL.md。',
      dependsOn: [1, 2, 3],
      expert: 'docs-coordinator',
    },
    {
      subject: '总结与建议',
      description: '基于研讨纪要输出总结：协议价值、关键看点、落地关注点、风险与建议（面向决策者，平实直接）。',
      dependsOn: [4],
      expert: 'team-lead',
    },
  ],
  deliverable: '一份智见点评研讨纪要（讨论稿）：材料要素拆解、各视角研判、融合结论、边界条件与风险提示、总结建议。',
  knowledge: SCENARIO_ID,
}

mkdirSync(join(KNOWLEDGE, 'scenarios'), { recursive: true })
writeFileSync(join(KNOWLEDGE, 'scenarios', `${SCENARIO_ID}.json`), `${JSON.stringify(scenario, null, 2)}\n`)
mkdirSync(join(KNOWLEDGE, 'scenarios', SCENARIO_ID), { recursive: true })
writeFileSync(join(KNOWLEDGE, 'scenarios', SCENARIO_ID, '研讨工作说明.md'),
  '# 研讨工作说明\n\n- 阵容默认：政策（仇保兴 bk-003）、存量循环（李宇嘉 bk-006）、宏观经济（邢自强 bk-004）、居住服务（杨现领 bk-033）+ 内置纪要/总结专家。\n- 如需换人：队长按 `shared/zhijian/专家总表.md` 与 `路由规则.md` 选择，`expert_teams_add_member(expert=bk-NNN)` 增补或移除默认成员。\n- 输出规范、匿名化、数字核实要求见 `shared/zhijian/SKILL.md`。\n')

console.log(`\n[ok] scenario ${SCENARIO_ID} (${scenario.experts.length} experts, ${scenario.tasks.length} tasks)`)
console.log(`\nImported ${expertIds.length} experts → ${KNOWLEDGE}`)
